name: Update Template Repository

on:
  repository_dispatch:
    types: [update-template]

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout template repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run npx create-akiradocs
      run: |
        npx create-akiradocs@latest update -y

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "chore: update template to latest version"
        title: "Automatic Template Update"
        body: |
          Automated template update using latest create-akiradocs package
        branch: template-update
        delete-branch: true